Some of the org-mode packages have already been loaded in the init.el
file. The init.el file also made sure that org mode was installed, so
no need to double-check that here. 

* Exporting
HTML and latex shown by default, let's add markdown:

#+BEGIN_SRC emacs-lisp
  (require 'ox)
  (require 'ox-md)
#+END_SRC

I don't like how timestamps look when org exports them. This makes it
more bearable. 

#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-export-filter-timestamp-functions
               #'endless/filter-timestamp)
  (defun endless/filter-timestamp (trans back _comm)
    "Remove <> around time-stamps."
    (pcase back
      ((or `jekyll `html)
       (replace-regexp-in-string "&[lg]t;" "" trans))
      (`latex
       (replace-regexp-in-string "[<>]" "" trans))))
  (setq-default org-display-custom-times t)
  ;;; Before you ask: No, removing the <> here doesn't work.
  (setq org-time-stamp-custom-formats
        '("<%d %b %Y>" . "<%d/%m/%y %a %H:%M>"))
#+END_SRC

Finally, I use xelatexmk so that org uses xelatex by default. I really
like the [[https://github.com/matze/mtheme][metropolis beamer theme.]] 

#+BEGIN_SRC emacs-lisp
  (setq org-latex-pdf-process (list "latexmk -f -shell-escape -xelatex %f"))
#+END_SRC

* Code blocks
  Org-babel is included in org. We just need to tell it which
  languages to load. And don't ask us if we're sure we want to run
  code blocks when we ~C-c C-c~. Finally, open the code block in the
  current window when we use ~C-'~ 

#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((R . t)
     (emacs-lisp . t)
     (latex . t)
     (python . t)))
  (setq org-confirm-babel-evaluate nil)
  ;; when working via C-c ' open in current window
  (setq org-src-window-setup 'current-window)
#+END_SRC

** Code block font locking
   This will make the contents of code blocks use the same font
   locking (syntax highlighting) as the major mode. It'll also make
   the tab key act like you want it to inside code blocks. 

#+BEGIN_SRC emacs-lisp
    (setq org-src-fontify-natively     t
          org-src-tab-acts-natively    t)
#+END_SRC

* Display images
  Org has a neat trick that it can display images. This is especially
  handy for when org-babel outputs a graph, since we can see the graph
  and then type around it. Let's turn that on:

#+BEGIN_SRC emacs-lisp
  (add-hook 'org-babel-after-execute-hook 'org-display-inline-images)   
  (add-hook 'org-mode-hook 'org-display-inline-images)
#+END_SRC

* Misc
Here are a few miscellaneous things that make org mode better. 
#+BEGIN_SRC emacs-lisp
  (setq org-pretty-entities          t
        org-support-shift-select     t)
  (use-package htmlize
    :ensure t)
#+END_SRC
