;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        indent-for-tab-command
        org-self-insert-command
        sp-backward-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        my/mc-hydra/mc/edit-lines-and-exit
        ))
