;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        end-of-visual-line
        indent-for-tab-command
        kill-visual-line
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        sp-backward-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        my/mc-hydra/mc/edit-lines-and-exit
        my/mc-hydra/mc/mark-all-in-region-regexp-and-exit
        my/mc-hydra/mc/mark-next-like-this
        my/mc-hydra/nil
        my/save-everything-noconfirm
        ))
